[package]
name = "cptv_common"
version = "0.1.0"
authors = ["jon hardie <jon@hardiesoft.com>"]
edition = "2018"


[dependencies]
#derivative = "1.0.3"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4.11"
log = "0.4.8"
